# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-08 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 8, 19, 1, 59, 207725, tzinfo=utc)),
        ),
    ]
